# Generated by Django 4.0.4 on 2022-04-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
